# Generated by Django 4.2.3 on 2024-10-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_parking_nome_alter_parkingspace_parking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('duration', models.PositiveIntegerField()),
            ],
        ),
    ]
