# Generated by Django 4.2.3 on 2024-10-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_parking_location_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='is_pcd',
            field=models.BooleanField(default=False),
        ),
    ]
